#!/bin/sh

bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9'
bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.50
bspc config focus_follows_pointer true

# Autostart programs:
sxhkd &
polybar -r &
"$TERMINAL"
